export {default as Bmi} from './Bmi'
export {default as Grade} from './Grade'
export {default as Calc} from './Calc'
export {default as Login} from './Login'
export {default as Counter} from './Counter'